# Generated by Django 5.0.3 on 2024-10-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='company',
            new_name='company_id',
        ),
    ]
