# Generated by Django 5.0.3 on 2024-10-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_company_userprofile_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_id',
            new_name='company',
        ),
    ]
